server: 
  port: 8765 
spring: 
  application: 
    name: api-gateway 
  cloud: 
    gateway: 
      discovery: 
        locator: 
          lower-case-service-id: true 
      routes: 
        - id: t1_clean_arch
          uri: lb://t1-clean-arch
          predicates: 
            - Path=/t1-clean-arch/**
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka 
management: 
  endpoints: 
    web: 
      exposure: 
        include: "*" 
  endpoint: 
    health: 
      show-details: always 
  gateway: 
    enabled: true